"use client";

import {
  ArrowRight,
  CheckCircle2,
  CircleDashed,
  Cpu,
  Database,
  KeyRound,
  LockKeyhole,
  MonitorDot,
  Radio,
  ShieldCheck,
  Wifi,
} from "lucide-react";

import Gc2ProtectedShell from "@/components/layout/gc2-protected-shell";
import { Gc2LinkButton } from "@/components/ui/gc2-button";
import { Gc2Notice, Gc2Status } from "@/components/ui/gc2-status";
import {
  Gc2Metric,
  Gc2SectionHeading,
  Gc2Surface,
} from "@/components/ui/gc2-surface";

const readinessSteps = [
  {
    number: "01",
    title: "Power the ESP32 controller",
    description:
      "Use the expected GreenCloud firmware and wait for the OLED pairing screen.",
    icon: Cpu,
  },
  {
    number: "02",
    title: "Read the six-character code",
    description:
      "The code is generated by the device and is not created manually in the web workspace.",
    icon: MonitorDot,
  },
  {
    number: "03",
    title: "Submit the protected claim",
    description:
      "Open the pairing studio, enter the code and provide the device label and garden zone.",
    icon: KeyRound,
  },
  {
    number: "04",
    title: "Wait for trusted approval",
    description:
      "Ownership, workspace projection and the first telemetry packet must complete before monitoring unlocks.",
    icon: Radio,
  },
];

function BoundaryRow({
  title,
  detail,
  state,
  ready,
}: {
  title: string;
  detail: string;
  state: string;
  ready: boolean;
}) {
  return (
    <div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 border-b border-[var(--gc2-line)] py-4 last:border-b-0">
      <div>
        <p className="m-0 text-sm font-bold text-[var(--gc2-ink)]">{title}</p>
        <p className="mt-1 text-xs leading-5 text-[var(--gc2-ink-soft)]">{detail}</p>
      </div>
      <Gc2Status tone={ready ? "success" : "neutral"}>{state}</Gc2Status>
    </div>
  );
}

export default function Gc2EmptyWorkspace({
  workspaceName,
  projectName,
  primaryZone,
  unreadNotifications,
}: {
  workspaceName: string;
  projectName: string;
  primaryZone: string;
  unreadNotifications: number;
}) {
  return (
    <Gc2ProtectedShell>
      <div className="gc2-stack">
        <Gc2SectionHeading
          kicker={`${workspaceName} · ${projectName}`}
          title="The workspace is ready. The first trusted device is not."
          description="GreenCloud keeps monitoring, analytics and irrigation controls unavailable until a real ESP32 completes protected pairing and publishes trustworthy telemetry."
          actions={
            <Gc2LinkButton href="/devices/add">
              Open pairing studio
              <ArrowRight aria-hidden="true" className="h-4 w-4" />
            </Gc2LinkButton>
          }
        />

        <div className="gc2-grid items-start">
          <Gc2Surface tone="raised" className="col-span-12 overflow-hidden p-0 lg:col-span-8">
            <div className="p-6 sm:p-8">
              <div className="flex flex-col gap-5 border-b border-[var(--gc2-line)] pb-6 sm:flex-row sm:items-start sm:justify-between">
                <div className="max-w-2xl">
                  <p className="gc2-kicker">First-device readiness</p>
                  <h2 className="gc2-heading-lg mt-3 max-w-[15ch]">
                    Pair before the workspace starts telling a plant story.
                  </h2>
                  <p className="gc2-copy mt-4">
                    There is no moisture, signal, environmental trend or irrigation history to display yet. The workspace will remain deliberately blank instead of filling the interface with demonstration values.
                  </p>
                </div>
                <Gc2Status tone="info">
                  <ShieldCheck aria-hidden="true" className="h-3.5 w-3.5" />
                  Output locked safely
                </Gc2Status>
              </div>

              <ol className="m-0 grid list-none gap-0 p-0">
                {readinessSteps.map(({ number, title, description, icon: Icon }) => (
                  <li
                    key={number}
                    className="grid grid-cols-[42px_minmax(0,1fr)] gap-4 border-b border-[var(--gc2-line)] py-5 last:border-b-0"
                  >
                    <span className="gc2-data pt-0.5 text-xs font-bold text-[var(--gc2-ink-muted)]">
                      {number}
                    </span>
                    <div className="flex items-start gap-3">
                      <Icon aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0 text-[var(--gc2-moss)]" />
                      <div>
                        <p className="m-0 text-sm font-bold text-[var(--gc2-ink)]">{title}</p>
                        <p className="mt-1 text-xs leading-5 text-[var(--gc2-ink-soft)]">
                          {description}
                        </p>
                      </div>
                    </div>
                  </li>
                ))}
              </ol>
            </div>

            <div className="border-t border-[var(--gc2-line)] bg-[var(--gc2-canvas-muted)] p-5 sm:p-6">
              <div className="grid gap-4 sm:grid-cols-3">
                <div className="flex items-start gap-3">
                  <Database aria-hidden="true" className="mt-0.5 h-5 w-5 text-[var(--gc2-success)]" />
                  <div>
                    <p className="m-0 text-sm font-bold text-[var(--gc2-ink)]">Private workspace</p>
                    <p className="mt-1 text-xs leading-5 text-[var(--gc2-ink-soft)]">
                      The authenticated owner scope already exists.
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <Wifi aria-hidden="true" className="mt-0.5 h-5 w-5 text-[var(--gc2-ink-muted)]" />
                  <div>
                    <p className="m-0 text-sm font-bold text-[var(--gc2-ink)]">Telemetry channel</p>
                    <p className="mt-1 text-xs leading-5 text-[var(--gc2-ink-soft)]">
                      No device packet has been accepted yet.
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <LockKeyhole aria-hidden="true" className="mt-0.5 h-5 w-5 text-[var(--gc2-warning)]" />
                  <div>
                    <p className="m-0 text-sm font-bold text-[var(--gc2-ink)]">Physical output</p>
                    <p className="mt-1 text-xs leading-5 text-[var(--gc2-ink-soft)]">
                      Pump and relay commands remain unavailable.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </Gc2Surface>

          <aside className="col-span-12 grid gap-5 lg:col-span-4">
            <Gc2Surface className="p-5 sm:p-6">
              <header className="border-b border-[var(--gc2-line)] pb-5">
                <p className="gc2-kicker">Workspace record</p>
                <h2 className="mt-2 text-xl font-bold text-[var(--gc2-ink)]">
                  Identity exists before telemetry
                </h2>
              </header>

              <div className="mt-5 grid gap-4">
                <Gc2Metric
                  label="Workspace"
                  value={workspaceName || "GreenCloud"}
                  detail="Authenticated private scope"
                />
                <Gc2Metric
                  label="Primary zone"
                  value={primaryZone || "Not named"}
                  detail="Editable in Workspace Settings"
                />
                <Gc2Metric
                  label="Unread notices"
                  value={unreadNotifications}
                  detail="Real workspace notification count"
                />
              </div>
            </Gc2Surface>

            <Gc2Surface className="p-5 sm:p-6">
              <header className="border-b border-[var(--gc2-line)] pb-5">
                <p className="gc2-kicker">Safety boundary</p>
                <h2 className="mt-2 text-lg font-bold text-[var(--gc2-ink)]">
                  What is ready and what stays locked
                </h2>
              </header>

              <div className="mt-1">
                <BoundaryRow
                  title="Owner session"
                  detail="Firebase Authentication protects the workspace route."
                  state="Ready"
                  ready
                />
                <BoundaryRow
                  title="Workspace identity"
                  detail="Project and primary-zone labels can already be reviewed."
                  state="Ready"
                  ready
                />
                <BoundaryRow
                  title="Canonical device owner"
                  detail="No ESP32 has completed the protected ownership flow."
                  state="Awaiting"
                  ready={false}
                />
                <BoundaryRow
                  title="Live telemetry"
                  detail="Moisture and signal remain unknown until a real packet arrives."
                  state="Unavailable"
                  ready={false}
                />
                <BoundaryRow
                  title="Irrigation command"
                  detail="Manual and automatic output stay blocked without a trusted device."
                  state="Locked"
                  ready={false}
                />
              </div>
            </Gc2Surface>

            <Gc2Notice
              tone="info"
              title="Nothing is broken"
              icon={<CircleDashed className="h-5 w-5" />}
            >
              This is the expected state for a new workspace. Continue only when the physical controller is powered and its OLED pairing code is visible.
            </Gc2Notice>

            <div className="flex flex-col gap-3 sm:flex-row lg:flex-col">
              <Gc2LinkButton href="/devices/add" className="justify-center">
                Pair the first ESP32
                <ArrowRight aria-hidden="true" className="h-4 w-4" />
              </Gc2LinkButton>
              <Gc2LinkButton href="/settings" variant="quiet" className="justify-center">
                Review workspace identity
                <CheckCircle2 aria-hidden="true" className="h-4 w-4" />
              </Gc2LinkButton>
            </div>
          </aside>
        </div>
      </div>
    </Gc2ProtectedShell>
  );
}
